### ISSUE TITLE
Add pyenv role

### ISSUE THREAD

**Issue by chuwy** [snowplow/ansible-playbooks#106]
[pyenv](https://github.com/yyuu/pyenv) is modern way to manage isolated python environments. It provides convenient way to install and switch between different interpreter versions (including implementations other than CPython).

It is better than current approach with pre-installing few interpreter versions because it allows to add new version with 1 command. Also [snowplow-python-tracker role](https://github.com/snowplow/ansible-playbooks/blob/master/roles/snowplow-python-tracker/tasks/main.yml) will be much shorter.

**Comment by alexanderdean** [comment]
Sounds great!
